import { Geist, Geist_Mono, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import MobileSidebar from "@/components/MobileSidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import NavbarWrapper from "@/components/NavbarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${poppins.variable} ${roboto.variable} ${geistMono.variable} antialiased `}
      >
        <SidebarProvider defaultOpen= {false}>
          <div className="min-h-screen w-full">
            <MobileSidebar />
            <NavbarWrapper/>
            <main className="flex-1">
              {children}
              <Footer />
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
